services:
  wazuh.manager:
    environment:
      INDEXER_USERNAME: ${INDEXER_USERNAME:?Set INDEXER_USERNAME}
      INDEXER_PASSWORD: ${INDEXER_PASSWORD:?Set INDEXER_PASSWORD}

  wazuh.dashboard:
    environment:
      INDEXER_USERNAME: ${INDEXER_USERNAME:?Set INDEXER_USERNAME}
      INDEXER_PASSWORD: ${INDEXER_PASSWORD:?Set INDEXER_PASSWORD}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:?Set DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:?Set DASHBOARD_PASSWORD}
