services:
  wazuh.manager:
    environment:
      INDEXER_USERNAME: ${INDEXER_USERNAME:?Set INDEXER_USERNAME}
      INDEXER_PASSWORD: ${INDEXER_PASSWORD:?Set INDEXER_PASSWORD}
    volumes:
      - ./tracked-config/wazuh-manager/shared/windows:/var/wazuh-manager/etc/shared/windows:ro
      - ./tracked-config/wazuh-manager/shared/linux:/var/wazuh-manager/etc/shared/linux:ro

  wazuh.dashboard:
    environment:
      INDEXER_USERNAME: ${INDEXER_USERNAME:?Set INDEXER_USERNAME}
      INDEXER_PASSWORD: ${INDEXER_PASSWORD:?Set INDEXER_PASSWORD}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:?Set DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:?Set DASHBOARD_PASSWORD}
